# bashrc
# shellcheck disable=SC2148

# Check for interactive
[[ $- = *i* ]] || return

# Disable control flow
stty -ixon 

# Shell options
shopt -s cdspell dirspell extglob cmdhist histappend no_empty_cmd_completion checkwinsize
shopt -u mailwarn

# GPG
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

# Jump between words with ctrl-(left|right)
bind '"\e[1;5C":forward-word'
bind '"\e[1;5D":backward-word'

bind -u forward-search-history

eval "$(dircolors -b)"

complete -cf sudo

for config in bash_aliases bash_functions bash_prompt bashrc."$HOSTNAME"; do
  # shellcheck disable=SC1090
  [[ -r $XDG_CONFIG_HOME/bash/$config ]] && . "$XDG_CONFIG_HOME/bash/$config"
done
unset config
