#!/bin/bash

set_prompt () {

    get_color256 () {
        echo -ne "\e[38;5;${1}m"
    }

    local green=10 blue=25 purple=55 light_blue=117 \
          black=240 gray=245 silver=251 

    local bold="\e[1m"
    local reset="\[\e[00m\]"
    local host_color pwd_color term_color

    if [[ "$HOSTNAME" =~ ^black.* ]]; then
        host_color="$(get_color256 $black)"
    elif [[ "$HOSTNAME" =~ ^blue.* ]]; then
        host_color="$(get_color256 $blue)"
    elif [[ "$HOSTNAME" =~ ^purple.* ]]; then
        host_color="$(get_color256 $purple)"
    elif [[ "$HOSTNAME" =~ ^silver.* ]]; then
        host_color="$(get_color256 $silver)"
    else
        host_color="$(get_color256 $green)"
    fi

    pwd_color="$(get_color256 $light_blue)"
    term_color="$(get_color256 $gray)"

    local host="${host_color}${bold}\h${reset}"
    local pwd="${pwd_color}${bold}\w${reset}"
    local term="${term_color}${bold}\$${reset}"

    local prompt="${host} ${pwd} ${term} "

    PS1=$prompt
}

set_prompt
unset set_prompt
