# bash aliases
# shellcheck shell=bash

alias sudo='sudo -v; sudo '
alias su='su -l'

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias ln='ln -i'

alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

alias mkdir='mkdir -p -v'

alias h='history'
alias hgrep='history | grep '

alias ls='ls -hF --color=auto'
alias ll='ls --group-directories-first -l'
alias la='ll -A'

alias l1='ls -1'
alias l.='ll -d .*'

alias lsd="ll | grep --color=never '^d'"        # only directories
alias lsr='ll -rt --group-directories-first'    # sort by date
alias lss='ll -Ssr'                             # sort by size
alias lst='tree -Csuh'                          # alternative to ls -R

alias path='echo -e ${PATH//:/\\n}'                 # pretty print path
alias libpath='echo -e ${LD_LIBRARY_PATH//:/\\n}'   # pretty print lib path

alias dmesg='sudo dmesg -HP'

alias df='df --human-readable --print-type'
alias du='du --human-readable --total --max-depth=1'

alias ping='ping -4'

alias ss='ss -plunt'
alias lsport='sudo lsof -i -n -P'

alias tmux='tmux new-session -ADX -s main'

alias dotfiles='/usr/bin/git --git-dir=$HOME/.cfg --work-tree=$HOME'

alias trash-empty='trash-empty --trash-dir=$HOME/.local/share/Trash'

alias shred='shred --verbose --iterations=5 --zero --remove'

alias wget='wget --continue --progress=bar --timestamping'

alias qmv='qmv --format=dual-column --options=space'
alias batch-rename='qmv'

alias reload-config='source ~/.bash_profile'
alias reload-shell='exec bash -l'

if [[ -r "/usr/share/bash-complete-alias/complete_alias" ]]; then
  . "/usr/share/bash-complete-alias/complete_alias"
  complete -F _complete_alias "${!BASH_ALIASES[@]}"
fi
