# bashrc
# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091

# Check for interactive
[[ $- = *i* ]] || return

# Disable control flow
stty -ixon

# Shell options
shopt -s cdspell dirspell extglob histappend histverify checkwinsize

# Configure pinentry to use the correct TTY
GPG_TTY=$(tty)
export GPG_TTY
gpg-connect-agent updatestartuptty /bye > /dev/null

# Use gpg-agent instead of ssh-agent
export SSH_AGENT_PID=""
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"

# Jump between words with ctrl-(left|right)
bind '"\e[1;5C":forward-word'
bind '"\e[1;5D":backward-word'

bind -u forward-search-history

eval "$(dircolors -b)"

if [[ -r "${XDG_CONFIG_HOME}/bash/bash_aliases" ]]; then
 . "${XDG_CONFIG_HOME}/bash/bash_aliases"
fi

if [[ -r "${XDG_CONFIG_HOME}/bash/bash_functions" ]]; then
 . "${XDG_CONFIG_HOME}/bash/bash_functions"
fi

if [[ -r "${XDG_CONFIG_HOME}/bash/bash_prompt" ]]; then
 . "${XDG_CONFIG_HOME}/bash/bash_prompt"
fi

if [[ -r "${XDG_CONFIG_HOME}/bash/bashrc.${HOSTNAME}" ]]; then
 . "${XDG_CONFIG_HOME}/bash/bashrc.${HOSTNAME}"
fi
